### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by DmitriiDenisov** [DmitriiDenisov/area_assessment#1]
Возможные шаги для улучшения:
- [ ] Узнать почему в ходе обучения горки появляются
- [ ] Новые спутниковые снимки (без угла)
——————————————————
- [x] На входе int8 вместо float. Итог: без нормировки намного медленнее обучается
- [x] Сделать выходную размерность не 2, а 1: уже реализовано в коде. Модель Кирилла (unet_old) изначально заточена под выход […,2]. Новые же объявления поддерживают как 1, так и 2
- [x] Сделать предсказание с пересечением: patches_toarray_overlap: Готово
- [x] Две сети для: а) Маски б) Спутника. Потом метаклассификатор: Готово
- [x] Попробовать какое качество если предсказание=Nokia_map: сделано, качество хуже, в районе 0.7
- [x] Переписать на новый Keras: готово
- [x] Поменять зоом: на 20 не обучается, на 19 норм, на 18 обучается примерно так же, как и z19
- [x] Поменять окошко с 64x64:  работает успешно с 128x128, динамика обучения: unet_old(128, 128, 3)

Динамика с output_channels = 2:
<img width="1238" alt="Screen Shot 2019-09-17 at 13 16 40" src="https://user-images.githubusercontent.com/36160558/65988145-598bb200-e498-11e9-8de8-68053d4451e6.png">
Динамика с output_channels = 1:
<img width="1236" alt="Screen Shot 2019-09-17 at 15 18 02" src="https://user-images.githubusercontent.com/36160558/65988154-5f819300-e498-11e9-9acf-1d05becb308f.png">

С окошком 256x256 не работает - не хватает памяти.
